### ISSUE TITLE
Supplementaries Stick cannot be broken once placed.

### ISSUE THREAD

**Issue by Gantros** [Darkorg69/BetterPunching#3]
Due to your mod, Supplementaries placeable stick cannot be broken once placed, which by default is a no tool break. I found a workaround by adding axes to their mod permissions, but mod compatibility would be nice for sticks and anything else that could be considered hand breakable and wouldn't cause damage.

**To Reproduce**
place a stick, try to break it.

**Expected behavior**
I expected to be able to remove it without harm. But I cannot remove it at all by hand or with any tool by default, as I had to go into the Supplementaries mod jar and add axe tool breaking.

**Which other mods caused the bug .**
This is an interaction with the Supplementaries mod.

**Comment by Darkorg69** [comment]
The bug is caused because of the missing mineable/axe tag. The stick is made out of wood material, and this means that you need  a proper tool to break it, as every other wooden block in the game. So supplementaries should add the tag on their end and the bug will be fixed. Mojang intruduced a new tag system in 1.17+. Probably they forgot to add the tag to the block.
