### ISSUE TITLE
[1.16.5] Dynamic Trees - trunk_shell block is unbreakable with any axe.

### ISSUE THREAD

**Issue by zargogo** [Darkorg69/BetterPunching#4]
**Describe the bug**
dynamictrees:trunk_shell blocks are unbreakable with any axe, since they have no tags.

**To Reproduce**
/Locatebiome byg:cika_mountains
Teleport there
Find a thick cika tree
Try chopping it down with an axe

**Expected behavior**
Trees should be choppable with the axe

**Which other mods caused the bug .**
https://www.curseforge.com/minecraft/mc-mods/dynamictrees
https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-byg
https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-terraforged
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go
https://www.curseforge.com/minecraft/mc-mods/terraforged

**Screenshots**
<img width="1440" alt="Screen Shot 2022-03-04 at 09 29 11" src="https://user-images.githubusercontent.com/17407989/156791844-de6b232d-f503-466e-a0da-d35a572f5b16.png">

**Additional context**
This is the fault of dynamictrees, since their trunk_shell blocks do not have any tags attached. Possible compatibility solution is to allow players to add custom "tree" blocks in your mod's config

**Comment by Darkorg69** [comment]
Issue is probably caused by improper or undefined proper ToolType for the block, 1.16.5 doesn't use the mineable tag system.
I'm working on updating the 1.16.5 version.
About the config to include custom "tree" blocks, this is way to complicated and unnessecary in my opinion, rather I think it will be better to check for "bugged" blocks and it will simply exclude them so the mod doesn't interfere with them. (In a situation similar with this, you would just be able to break the block with hands), and on top of that a simple config which will just exclude blocks, so if the check fails you can do it manually.
